import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";
import styles from "./barang/barang.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className={styles.header}>
          {/* <img src="./images/logo.png"/> */}
          <Image
            src={"/images/logo.png"}
            alt="Logo Teknokrat"
            width={400}
            height={100}
            priority
          />
        </header>
        {children}

        {/* buat text toaster */}
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              color: "white",
              backgroundColor: "black",
            },
          }}
        />

        {/* footer */}
        <footer className={styles.footer}>&copy; 2025 - Suyaguus</footer>
      </body>
    </html>
  );
}
